import { DatabaseSchema, AboutPageSettings, ServicesPageSettings } from './types';

export const INITIAL_ADMIN_EMAIL = 'reddphotographycreations@gmail.com';
export const INITIAL_ADMIN_PASSWORD = 'ReddAdmin2024!#';

export const initialAboutData: AboutPageSettings = {
  eyebrow: 'About The Director & Studio',
  headline: 'A relentless pursuit of visual purity.',
  headlineItalic: 'visual purity',
  portraitImageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1200&auto=format&fit=crop',
  directorName: 'Kiran Redd',
  directorRole: 'Creative Director',
  directorSubRole: 'Founding Principal, REDD Studio',
  bioParagraph1:
    'REDD Photography Creations is an international editorial and commercial photography studio directed by Kiran Redd. Combining modernist discipline, high-contrast chiaroscuro, and uncompromising minimalism, REDD transforms moments into enduring pieces of visual art. With an eye shaped by contemporary architecture and classic Italian renaissance lighting, every frame is stripped of superfluous distraction to expose sheer emotion, texture, and refined aesthetic precision.',
  bioQuote:
    'Modernism in photography is not merely about cold lines—it is the deliberate stripping away of clutter to allow genuine human truth, organic texture, and form to command the viewer’s full attention.',
  bioParagraph2:
    'Whether orchestrating a 20-person crew on a high-fashion campaign in Milan, working one-on-one in an intimate and empowering fine-art boudoir setting, or crafting an authoritative corporate portrait, Kiran’s method is grounded in patience, anatomical awareness, and absolute technical mastery.',
  milestones: [
    { id: 'mile-1', value: '12+', label: 'Years Behind Lens', order: 1 },
    { id: 'mile-2', value: '18', label: 'Solo Exhibitions', order: 2 },
    { id: 'mile-3', value: '14', label: 'International Awards', order: 3 },
  ],
  honorsEyebrow: 'Recognition',
  honorsTitle: 'Features & Honors',
  honorsList: [
    { id: 'hon-1', title: 'VOGUE', subtitle: 'Scandinavia & Italia', order: 1 },
    { id: 'hon-2', title: 'VANITY FAIR', subtitle: 'Executive Portraiture', order: 2 },
    { id: 'hon-3', title: 'ARCH DIGEST', subtitle: 'Commercial Architecture', order: 3 },
    { id: 'hon-4', title: 'PX3 PARIS', subtitle: 'Gold Award Winner', order: 4 },
  ],
  gearTitleEyebrow: 'The Optical Arsenal',
  gearTitle: 'Curated Production Gear',
  ctaTitle: 'Commission a Visual Narrative',
  ctaDescription: 'Available for private sessions, high-fashion campaigns, and commercial briefs globally.',
  ctaButtonText: 'Request Shoot Consultation',
  ctaButtonLink: '/contact',
};

export const initialServicesData: ServicesPageSettings = {
  eyebrow: 'Bespoke Production Services',
  headline: 'Disciplines & Commissions',
  headlineItalic: 'Commissions',
  introText:
    'Every project is treated as an individual piece of art. Explore our specialized services across the five pillars of REDD Photography Creations.',
  offerings: [
    {
      id: 'serv-fashion',
      category: 'fashion',
      title: 'Haute Couture & Editorial Fashion',
      eyebrow: 'Editorial Campaigns & Lookbooks',
      description:
        'Designed for high-end fashion labels, independent designers, and editorial publications. We craft architectural, dynamic narratives that treat garments as sculptural art in motion.',
      features: [
        'Full moodboard, concept development, and casting support',
        'Multi-light studio setup or location scouts (brutalist, natural, urban)',
        'Lookbook and high-res campaign assets formatted for print & web',
        'Hair, makeup, and wardrobe styling coordination upon request',
      ],
      idealFor: 'Designers, magazines, modeling agencies, and couture ateliers',
      investment: 'From $6,500',
      buttonText: 'Inquire About This Service',
      buttonLink: '/contact?category=fashion',
      enabled: true,
      order: 1,
    },
    {
      id: 'serv-boudoir',
      category: 'boudoir',
      title: 'Fine-Art Boudoir & Intimate Form',
      eyebrow: 'Empowering, Safe & Tasteful Fine-Art',
      description:
        'An artistic celebration of feminine form, self-love, and vulnerability. Executed in a completely safe, private, and discreet setting using soft natural window light and Belgian linen textures.',
      features: [
        'Strict privacy guarantee and confidential image handling',
        'Pre-session wardrobe consultation and styling guide',
        'Gentle, body-affirming posing guidance (no prior modeling experience needed)',
        'Signature fine-art retouching focusing on natural skin fidelity and tones',
      ],
      idealFor: 'Milestone celebrations, personal empowerment, bridal gifts, and fine-art collectors',
      investment: 'From $2,800',
      buttonText: 'Inquire About This Service',
      buttonLink: '/contact?category=boudoir',
      enabled: true,
      order: 2,
    },
    {
      id: 'serv-portraits',
      category: 'portraits',
      title: 'Cinematic & Executive Portraiture',
      eyebrow: 'Personal Branding & Character Studies',
      description:
        'Far beyond standard corporate headshots. We construct moody, high-contrast chiaroscuro character studies that project gravity, intellect, and timeless distinction.',
      features: [
        'One-on-one focused studio session with tethered monitor review',
        'Multiple lighting setups (dramatic rim light, Rembrandt key, soft daylight)',
        'Master retouched portraits delivered in web and gallery print formats',
        'Commercial usage license for press releases, books, and digital presence',
      ],
      idealFor: 'CEOs, founders, artists, directors, authors, and thought leaders',
      investment: 'From $1,800',
      buttonText: 'Inquire About This Service',
      buttonLink: '/contact?category=portraits',
      enabled: true,
      order: 3,
    },
    {
      id: 'serv-events',
      category: 'events',
      title: 'High-Society Galas & Runway Events',
      eyebrow: 'Documentary Elegance & VIP Gatherings',
      description:
        'Discreet, candid visual documentation of premier events. We capture unposed laughter, kinetic ballroom atmosphere, and VIP elegance without invasive flash interruption.',
      features: [
        'Unobtrusive photojournalistic coverage by experienced lead photographer',
        'Same-night or 24-hour press highlight delivery for PR wire & social media',
        'Full high-resolution master collection with complete archival color grades',
        'Red carpet arrival and ambient architectural venue coverage',
      ],
      idealFor: 'Luxury charity galas, fashion shows, private brand dinners, and cultural summits',
      investment: 'From $4,500',
      buttonText: 'Inquire About This Service',
      buttonLink: '/contact?category=events',
      enabled: true,
      order: 4,
    },
    {
      id: 'serv-commercial',
      category: 'commercial',
      title: 'Commercial & Advertising Campaigns',
      eyebrow: 'Product, Automotive & Architectural Imagery',
      description:
        'Hyper-focused commercial precision. Shot on 100-megapixel medium format sensors to highlight microscopic craftsmanship, materials, and luxury brand prestige.',
      features: [
        'Macro precision lighting for timepieces, jewelry, and perfumery',
        'Architectural interior & exterior twilight captures with perspective control',
        'Global buyout and worldwide digital/print advertising licensing',
        'Extensive digital compositing, focus stacking, and color accuracy certification',
      ],
      idealFor: 'Horology brands, architects, luxury hospitality, and premium consumer goods',
      investment: 'Custom Quote',
      buttonText: 'Inquire About This Service',
      buttonLink: '/contact?category=commercial',
      enabled: true,
      order: 5,
    },
  ],
  journeyEyebrow: 'The Experience',
  journeyTitle: 'From Concept to Master Print',
  journeySteps: [
    {
      id: 'step-1',
      stepNumber: 'STEP 01',
      title: 'Vision Consultation',
      description:
        'We align on your creative intent, moodboards, color palette, location requirements, and styling references.',
    },
    {
      id: 'step-2',
      stepNumber: 'STEP 02',
      title: 'Production Day',
      description:
        'Meticulous execution with tethered medium-format capture, continuous direction, and stress-free atmosphere.',
    },
    {
      id: 'step-3',
      stepNumber: 'STEP 03',
      title: 'Master Color Grading',
      description:
        'Individual tonal sculpting, frequency separation retouching, and cinematic color curves applied by hand.',
    },
    {
      id: 'step-4',
      stepNumber: 'STEP 04',
      title: 'Archival Delivery',
      description:
        'Private digital cloud gallery with full-resolution master files and optional handmade fine-art prints.',
    },
  ],
  ctaTitle: 'Commission a Bespoke Production',
  ctaDescription: 'Whether an editorial lookbook, intimate portraiture, or luxury brand advertising.',
  ctaButtonText: 'Initiate Booking Proposal',
  ctaButtonLink: '/contact',
};

export const initialSeedData: DatabaseSchema = {
  admin: {
    email: INITIAL_ADMIN_EMAIL,
    passwordHash: '', // Will be hashed upon initial DB boot
    name: 'REDD Director',
  },
  settings: {
    brandName: 'REDD Photography Creations',
    artistName: 'Kiran Redd',
    email: 'reddphotographycreations@gmail.com',
    phone: '+1 (555) 382-7333',
    location: 'New York • Paris • Milan • Worldwide',
    heroTagline: 'Raw Elegance, Architectural Form & Editorial Soul.',
    heroSubtitle: 'Minimalist visual storytelling for haute couture, intimate boudoir, cinematic portraits, high-profile events, and commercial campaigns.',
    bio: 'REDD Photography Creations is an international editorial and commercial photography studio directed by Kiran Redd. Combining modernist discipline, high-contrast chiaroscuro, and uncompromising minimalism, REDD transforms moments into enduring pieces of visual art. With an eye shaped by contemporary architecture and classic Italian renaissance lighting, every frame is stripped of superfluous distraction to expose sheer emotion, texture, and refined aesthetic precision.',
    artistPhilosophy: 'We believe photography is not the act of capturing everything, but the art of eliminating the non-essential until only resonance remains. Form, shadow, gesture, and unforced authenticity.',
    yearsExperience: 12,
    exhibitionsCount: 18,
    awardsCount: 14,
    gearKit: {
      cameras: [
        'Hasselblad H6D-100c Medium Format',
        'Leica M11 Rangefinder',
        'Sony α1 Flagship Mirrorless'
      ],
      lenses: [
        'Hasselblad HC 100mm f/2.2',
        'Leica Summilux-M 50mm f/1.4 ASPH',
        'Sony FE 85mm f/1.4 GM II',
        'Sony FE 35mm f/1.4 GM'
      ],
      lighting: [
        'Profoto Pro-11 2400 AirTTL Generator',
        'Profoto B10X Plus Monolights',
        'Broncolor Para 133 HR Reflector'
      ]
    },
    // Logo & Branding
    logoUrl: '',
    logoHeight: 36,
    logoText: 'REDD',
    logoSubtitle: 'Photography Creations',

    // Header Menu Navigation
    headerNav: [
      { id: 'nav-1', label: 'WORK', href: '/#work', isExternal: false, order: 1, enabled: true },
      { id: 'nav-2', label: 'ABOUT', href: '/about', isExternal: false, order: 2, enabled: true },
      { id: 'nav-3', label: 'SERVICES', href: '/services', isExternal: false, order: 3, enabled: true },
      { id: 'nav-4', label: 'CONTACT', href: '/contact', isExternal: false, order: 4, enabled: true },
    ],
    headerCtaText: 'Book Session',
    headerCtaLink: '/contact',
    headerCtaEnabled: true,

    // Footer Configuration
    footerBio: 'Modernist visual storytelling across haute couture, fine-art boudoir, cinematic portraits, high-society events, and brand commercial campaigns. Stripping away the excess to reveal uncompromising form and soul.',
    footerHeadquarters: 'New York • Paris • Milan • Worldwide',
    footerInquiriesTitle: 'Inquiries & Bookings',
    footerInquiriesText: 'Accepting select editorial commissions, bespoke boudoir sessions, and commercial brand productions globally.',
    footerInquiriesEmail: 'reddphotographycreations@gmail.com',
    footerInquiriesPhone: '+1 (555) 382-7333',
    footerCtaText: 'Request Booking Proposal',
    footerCtaLink: '/contact',
    footerCopyright: '© {year} REDD Photography Creations. All photographic rights reserved.',
    showAdminInFooter: true,

    socials: {
      instagram: 'https://instagram.com/reddphotographycreations',
      behance: 'https://behance.net/reddcreations',
      vimeo: 'https://vimeo.com/reddphotography',
      linkedin: 'https://linkedin.com/in/reddphotography',
      twitter: 'https://twitter.com/reddphotography',
    }
  },
  photos: [
    // --- FASHION ---
    {
      id: 'fash-01',
      title: 'Monolith in Obsidian',
      category: 'fashion',
      imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Vogue Scandinavia Issue #14',
      story: 'Sculptural silhouette editorial shot in an abandoned brutalist pavilion near Copenhagen. The play between fluid couture silk and rigid raw concrete.',
      year: '2024',
      location: 'Copenhagen, Denmark',
      camera: 'Hasselblad H6D-100c',
      lens: 'HC 100mm f/2.2',
      aperture: 'f/4.0',
      shutterSpeed: '1/250s',
      iso: '64',
      featured: true,
      order: 1,
      createdAt: '2024-01-15T10:00:00Z'
    },
    {
      id: 'fash-02',
      title: 'Crimson Veil & Solitude',
      category: 'fashion',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Maison de L’Ombre',
      story: 'Avant-garde winter collection presentation featuring dramatic monochromatic textures and bold scarlet contrast.',
      year: '2024',
      location: 'Milan, Italy',
      camera: 'Sony α1',
      lens: 'FE 85mm f/1.4 GM II',
      aperture: 'f/2.0',
      shutterSpeed: '1/500s',
      iso: '100',
      featured: true,
      order: 2,
      createdAt: '2024-02-10T12:30:00Z'
    },
    {
      id: 'fash-03',
      title: 'Structural Drape',
      category: 'fashion',
      imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'wide',
      client: 'Kinetics Fashion Quarterly',
      story: 'Exploration of garment movement in zero ambient breeze, relying on high-speed flash duration to freeze textile suspension.',
      year: '2023',
      location: 'Paris Studio 7',
      camera: 'Leica M11',
      lens: 'Summilux-M 50mm f/1.4 ASPH',
      aperture: 'f/2.8',
      shutterSpeed: '1/800s',
      iso: '125',
      featured: false,
      order: 3,
      createdAt: '2023-11-20T14:15:00Z'
    },
    {
      id: 'fash-04',
      title: 'Linear Geometry & Satin',
      category: 'fashion',
      imageUrl: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Atelier Noir NYC',
      story: 'A study in sharp tailored shoulder lines, geometric shadows, and contemporary street couture.',
      year: '2024',
      location: 'SoHo, New York',
      camera: 'Sony α1',
      lens: 'FE 50mm f/1.2 GM',
      aperture: 'f/1.8',
      shutterSpeed: '1/1000s',
      iso: '100',
      featured: false,
      order: 4,
      createdAt: '2024-03-05T09:40:00Z'
    },

    // --- BOUDOIR ---
    {
      id: 'boud-01',
      title: 'Curves of Light & Linen',
      category: 'boudoir',
      imageUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Private Fine Art Commission',
      story: 'Natural morning backlight sculpting soft contours across unbleached Belgian linen. Intimate, empowering, and strictly artistic.',
      year: '2024',
      location: 'Private Loft, Brooklyn',
      camera: 'Leica M11',
      lens: 'Summilux-M 50mm f/1.4 ASPH',
      aperture: 'f/1.4',
      shutterSpeed: '1/320s',
      iso: '200',
      featured: true,
      order: 5,
      createdAt: '2024-04-01T08:15:00Z'
    },
    {
      id: 'boud-02',
      title: 'Shadow play on Silk',
      category: 'boudoir',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'square',
      client: 'Elegance Fine Art Series',
      story: 'Window slatted blind patterns cast across shoulders and neckline, exploring vulnerability and inner strength through monochrome tones.',
      year: '2023',
      location: 'SoHo Suite, New York',
      camera: 'Hasselblad H6D-100c',
      lens: 'HC 100mm f/2.2',
      aperture: 'f/2.8',
      shutterSpeed: '1/160s',
      iso: '100',
      featured: false,
      order: 6,
      createdAt: '2023-10-18T16:20:00Z'
    },
    {
      id: 'boud-03',
      title: 'Embrace of the Form',
      category: 'boudoir',
      imageUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Self-Love & Empowerment Project',
      story: 'Subtle chiaroscuro lighting celebrating feminine posture and delicate grace with zero digital retouching distortion.',
      year: '2024',
      location: 'Parisian Penthouse',
      camera: 'Sony α1',
      lens: 'FE 85mm f/1.4 GM II',
      aperture: 'f/1.8',
      shutterSpeed: '1/250s',
      iso: '160',
      featured: true,
      order: 7,
      createdAt: '2024-02-28T11:00:00Z'
    },

    // --- PORTRAITS ---
    {
      id: 'port-01',
      title: 'The Director’s Gaze',
      category: 'portraits',
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Vanity Fair Executive Series',
      story: 'Cinematic portrait of acclaimed European filmmaker. Minimal key light with deep negative fill to emphasize intellectual intensity.',
      year: '2024',
      location: 'Berlin, Germany',
      camera: 'Hasselblad H6D-100c',
      lens: 'HC 100mm f/2.2',
      aperture: 'f/3.2',
      shutterSpeed: '1/200s',
      iso: '64',
      featured: true,
      order: 8,
      createdAt: '2024-03-12T15:30:00Z'
    },
    {
      id: 'port-02',
      title: 'Ethereal Melancholy',
      category: 'portraits',
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'square',
      client: 'Acoustic Soul Album Art',
      story: 'Raw analog warmth captured under single tungsten spotlight during recording sessions in East London.',
      year: '2023',
      location: 'London, UK',
      camera: 'Leica M11',
      lens: 'Noctilux-M 50mm f/0.95 ASPH',
      aperture: 'f/1.2',
      shutterSpeed: '1/125s',
      iso: '400',
      featured: false,
      order: 9,
      createdAt: '2023-12-05T19:45:00Z'
    },
    {
      id: 'port-03',
      title: 'Grace in Monolith',
      category: 'portraits',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'Prima Ballerina Study',
      story: 'Poise and inner composure of leading soloist before opening night at Lincoln Center.',
      year: '2024',
      location: 'New York, USA',
      camera: 'Sony α1',
      lens: 'FE 135mm f/1.8 GM',
      aperture: 'f/2.0',
      shutterSpeed: '1/640s',
      iso: '160',
      featured: true,
      order: 10,
      createdAt: '2024-01-22T17:10:00Z'
    },

    // --- EVENTS ---
    {
      id: 'eve-01',
      title: 'Met Gala Midnight Veil',
      category: 'events',
      imageUrl: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'wide',
      client: 'Vogue Special Coverage',
      story: 'The kinetic elegance of high society gathering on grand illuminated steps under candlelight.',
      year: '2024',
      location: 'Metropolitan Museum, NY',
      camera: 'Leica M11',
      lens: 'Summilux-M 35mm f/1.4 ASPH',
      aperture: 'f/1.4',
      shutterSpeed: '1/160s',
      iso: '800',
      featured: true,
      order: 11,
      createdAt: '2024-05-07T23:20:00Z'
    },
    {
      id: 'eve-02',
      title: 'The Crystal Toast',
      category: 'events',
      imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'wide',
      client: 'Dom Pérignon Private Gala',
      story: 'Unstaged, authentic laughter amidst vintage champagne and crystal chandelier reflections in Lake Como.',
      year: '2023',
      location: 'Villa Balbianello, Italy',
      camera: 'Sony α1',
      lens: 'FE 24-70mm f/2.8 GM II',
      aperture: 'f/2.8',
      shutterSpeed: '1/200s',
      iso: '1600',
      featured: false,
      order: 12,
      createdAt: '2023-09-14T21:15:00Z'
    },
    {
      id: 'eve-03',
      title: 'Paris Fashion Week Backstage',
      category: 'events',
      imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'wide',
      client: 'Balenciaga Runway Team',
      story: 'Thirty seconds before lights hit the runway. Intense focus, steam from irons, and final hem adjustments.',
      year: '2024',
      location: 'Grand Palais, Paris',
      camera: 'Leica M11',
      lens: 'Summicron-M 28mm f/2 ASPH',
      aperture: 'f/2.0',
      shutterSpeed: '1/320s',
      iso: '1250',
      featured: true,
      order: 13,
      createdAt: '2024-03-02T19:00:00Z'
    },

    // --- COMMERCIAL ---
    {
      id: 'comm-01',
      title: 'Chronograph in Titanium',
      category: 'commercial',
      imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'square',
      client: 'Chronometrie Genevoise',
      story: 'Precision macro commercial campaign highlighting hand-beveled edges and sunburst dial reflections on matte black slate.',
      year: '2024',
      location: 'Geneva, Switzerland',
      camera: 'Hasselblad H6D-100c',
      lens: 'Macro 120mm f/4 II',
      aperture: 'f/11',
      shutterSpeed: '1/125s',
      iso: '64',
      featured: true,
      order: 14,
      createdAt: '2024-04-18T14:00:00Z'
    },
    {
      id: 'comm-02',
      title: 'Essence Noire Parfumerie',
      category: 'commercial',
      imageUrl: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'tall',
      client: 'L’Artisan Parfumeur Paris',
      story: 'Smoky, amber reflections passing through fluted glass flacon on volcanic basalt stone.',
      year: '2024',
      location: 'Studio Marais, Paris',
      camera: 'Sony α1',
      lens: 'FE 90mm f/2.8 Macro G OSS',
      aperture: 'f/8.0',
      shutterSpeed: '1/160s',
      iso: '100',
      featured: false,
      order: 15,
      createdAt: '2024-05-11T16:40:00Z'
    },
    {
      id: 'comm-03',
      title: 'The Concrete Pavilion',
      category: 'commercial',
      imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1600&auto=format&fit=crop',
      aspectRatio: 'wide',
      client: 'Architectural Digest & Studio Tadao',
      story: 'Symmetrical study of raw concrete, timber accents, and cantilevered infinity pool at twilight.',
      year: '2023',
      location: 'Kyoto, Japan',
      camera: 'Hasselblad H6D-100c',
      lens: 'HC 24mm f/4.8',
      aperture: 'f/11',
      shutterSpeed: '1.5s',
      iso: '64',
      featured: true,
      order: 16,
      createdAt: '2023-11-04T18:20:00Z'
    }
  ],
  inquiries: [
    {
      id: 'inq-01',
      name: 'Elena Rostova',
      email: 'elena.rostova@maisonmode.fr',
      phone: '+33 6 42 19 88 01',
      category: 'fashion',
      preferredDate: '2025-04-15',
      location: 'Paris, France',
      budgetRange: '$10,000 - $25,000',
      message: 'Bonjour Kiran, we are preparing our Autumn/Winter couture lookbook and campaign. We loved your Monolith in Obsidian series and want a similar architectural brutalist sensibility for our 12-look collection.',
      status: 'new',
      notes: 'High priority couture client. Reply with Paris shoot availability.',
      createdAt: '2024-09-15T11:20:00Z'
    },
    {
      id: 'inq-02',
      name: 'Marcus Sterling',
      email: 'm.sterling@luminaryholdings.com',
      phone: '+1 (212) 555-0198',
      category: 'events',
      preferredDate: '2025-05-20',
      location: 'The Glasshouse, Manhattan',
      budgetRange: '$15,000+',
      message: 'Looking for discreet, high-end editorial coverage for our annual global leadership summit and private gala dinner. Need documentary-style elegance rather than standard corporate event snapshots.',
      status: 'contacted',
      notes: 'Sent PDF rate card and portfolio link.',
      createdAt: '2024-09-12T14:45:00Z'
    },
    {
      id: 'inq-03',
      name: 'Claire Beauchamp',
      email: 'claire.beauchamp@gmail.com',
      phone: '+1 (415) 555-7721',
      category: 'boudoir',
      preferredDate: '2025-03-10',
      location: 'San Francisco / Big Sur',
      budgetRange: '$3,500 - $5,000',
      message: 'I am celebrating my 40th birthday and would love an intimate, tasteful fine-art boudoir session. Your work with natural light and linen is breathtaking. What is your preparation and studio process?',
      status: 'new',
      notes: 'Provide boudoir experience guide and comfort protocols.',
      createdAt: '2024-09-17T09:10:00Z'
    }
  ],
  categories: [
    {
      id: 'cat-fashion',
      slug: 'fashion',
      label: 'Haute Couture & Fashion',
      description: 'Sculptural silhouettes, couture lookbooks, and high-contrast movement studies.',
      enabled: true,
      order: 1,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: 'cat-boudoir',
      slug: 'boudoir',
      label: 'Fine-Art Boudoir',
      description: 'Intimate, empowering, and tasteful fine-art celebrating feminine form in soft natural light.',
      enabled: true,
      order: 2,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: 'cat-portraits',
      slug: 'portraits',
      label: 'Cinematic Portraits',
      description: 'Chiaroscuro character studies, executive branding, and studio lighting.',
      enabled: true,
      order: 3,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: 'cat-events',
      slug: 'events',
      label: 'High-Society Events & Galas',
      description: 'Discreet gala photojournalism, runway backstage, and VIP gatherings.',
      enabled: true,
      order: 4,
      createdAt: '2024-01-01T00:00:00Z',
    },
    {
      id: 'cat-commercial',
      slug: 'commercial',
      label: 'Commercial & Advertising',
      description: 'Macro precision for horology/timepieces, perfumery, and minimalist architecture.',
      enabled: true,
      order: 5,
      createdAt: '2024-01-01T00:00:00Z',
    },
  ],
  heroSlides: [
    {
      id: 'slide-01',
      title: 'Monolith in Obsidian',
      subtitle: 'Vogue Scandinavia • Autumn / Winter Editorial',
      tagline: 'Haute Couture & Movement',
      description: 'Sculptural silhouette editorial captured in an abandoned brutalist pavilion near Copenhagen. The interplay between fluid silk and rigid concrete.',
      imageUrl: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=2000&auto=format&fit=crop',
      category: 'fashion',
      buttonText: 'Explore Fashion Editorial',
      buttonLink: '#work',
      secondaryButtonText: 'Initiate Commission',
      secondaryButtonLink: '/contact',
      textAlignment: 'left',
      fontStyle: 'editorial-serif',
      titleCase: 'uppercase',
      accentColor: 'crimson',
      overlayOpacity: 0.55,
      order: 1,
      enabled: true,
      createdAt: '2024-01-10T10:00:00Z',
    },
    {
      id: 'slide-02',
      title: 'Veil of Dawn & Linen',
      subtitle: 'Private Fine-Art Boudoir Portfolio',
      tagline: 'Intimate Fine-Art Boudoir',
      description: 'Natural raking morning light across European raw linen. Celebrating feminine form, emotional vulnerability, and pure unforced grace.',
      imageUrl: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=2000&auto=format&fit=crop',
      category: 'boudoir',
      buttonText: 'Discover Boudoir Series',
      buttonLink: '#work',
      secondaryButtonText: 'Private Booking',
      secondaryButtonLink: '/contact',
      textAlignment: 'center',
      fontStyle: 'editorial-serif',
      titleCase: 'uppercase',
      accentColor: 'gold',
      overlayOpacity: 0.5,
      order: 2,
      enabled: true,
      createdAt: '2024-01-15T12:00:00Z',
    },
    {
      id: 'slide-03',
      title: 'The Alchemist’s Study',
      subtitle: 'Master Character & Executive Series',
      tagline: 'Cinematic Chiaroscuro Portraits',
      description: 'Caravaggesque single-source key lighting revealing authentic character, dramatic depth, and enduring emotional gravity.',
      imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=2000&auto=format&fit=crop',
      category: 'portraits',
      buttonText: 'View Portrait Works',
      buttonLink: '#work',
      secondaryButtonText: 'Reserve Studio Session',
      secondaryButtonLink: '/contact',
      textAlignment: 'left',
      fontStyle: 'editorial-serif',
      titleCase: 'uppercase',
      accentColor: 'crimson',
      overlayOpacity: 0.6,
      order: 3,
      enabled: true,
      createdAt: '2024-01-20T14:00:00Z',
    },
    {
      id: 'slide-04',
      title: 'Haute Horlogerie & Shadow',
      subtitle: 'Swiss Masterpiece Advertising Campaign',
      tagline: 'Commercial & Architectural Art',
      description: 'High-precision macro lighting isolating titanium bevels, tourbillon mechanics, and microscopic engineering excellence.',
      imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=2000&auto=format&fit=crop',
      category: 'commercial',
      buttonText: 'Explore Commercial Works',
      buttonLink: '#work',
      secondaryButtonText: 'Brand Inquiries',
      secondaryButtonLink: '/contact',
      textAlignment: 'right',
      fontStyle: 'modern-sans',
      titleCase: 'uppercase',
      accentColor: 'white',
      overlayOpacity: 0.65,
      order: 4,
      enabled: true,
      createdAt: '2024-01-25T16:00:00Z',
    },
  ],
  seo: {
    metaTitle: 'REDD Photography Creations | Haute Couture, Fine-Art Boudoir, Portraits & Commercial',
    metaDescription:
      'International modernist photography studio directed by Kiran Redd. Specializing in sculptural fashion lookbooks, intimate fine-art boudoir, cinematic chiaroscuro portraits, and luxury commercial advertising.',
    keywords: [
      'REDD Photography Creations',
      'Kiran Redd',
      'Haute Couture Photography',
      'Fine-Art Boudoir Photography',
      'Cinematic Portraits',
      'Luxury Commercial Photography',
      'Modernist Photography Studio',
      'Hasselblad Medium Format',
      'High-Society Gala Photography',
      'Editorial Lookbook Direction',
    ],
    canonicalUrl: 'https://reddphotographycreations.com',
    robotsIndex: true,
    robotsFollow: true,
    ogTitle: 'REDD Photography Creations — Raw Elegance & Architectural Form',
    ogDescription:
      'Minimalist visual storytelling for haute couture, intimate boudoir, cinematic portraits, high-profile events, and commercial campaigns.',
    ogImageUrl:
      'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1600&auto=format&fit=crop',
    metaPixelId: '',
    metaDomainVerification: '',
    facebookAppId: '',
    twitterCardType: 'summary_large_image',
    twitterHandle: '@reddphotography',
    googleAnalyticsId: '',
    googleTagManagerId: '',
    googleSiteVerification: '',
    enableSchemaOrg: true,
    schemaType: 'Photographer',
    allowGptBot: true,
    allowClaudeBot: true,
    allowPerplexityBot: true,
    allowGoogleExtended: true,
    allowAppleBot: true,
    allowCommonCrawl: true,
    aiStudioSynopsis:
      'REDD Photography Creations is an international modernist photography studio founded by Kiran Redd, operating across New York, Paris, Milan, and worldwide. Specializing in 5 core disciplines: Haute Couture & Fashion, Fine-Art Boudoir, Cinematic Portraits, High-Society Events & Galas, and Luxury Commercial Advertising. Shot on 100-megapixel medium format Hasselblad and Leica M11 systems with Profoto high-speed strobes. Commission inquiries: reddphotographycreations@gmail.com.',
  },
  about: initialAboutData,
  services: initialServicesData,
};


